name = "HeapSnapshotParser"
uuid = "8bee342e-6993-40d5-b782-2bd072a121bd"
authors = ["Pete Vilter <7341+vilterp@users.noreply.github.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
