name = "HeapSnapshotParser"
uuid = "8bee342e-6993-40d5-b782-2bd072a121bd"
authors = ["Pete Vilter <7341+vilterp@users.noreply.github.com>"]
version = "0.1.0"

[deps]
FlameGraphs = "08572546-2f56-4bcf-ba4e-bab62c3a3f89"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
